spring.application.name=detectia
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base3
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Configuracion JWT
jwt.secret=detectiaProyectoFinalModulo3Semestre3SiAlguienDescubreEsteSecretoGGEZ

#contra usuarios
app.default-password=1234567890

#MIXTAS
#GEMINI
gemini.api.key=AIzaSyA8h8GQui-gcsX6vWACYjKDp6tC91DSd_4
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

#Hive Moderation
hive.api.key=zbk2CG3DZkb0ERJn1nNXtg==
#epiFvH+Cyoi1eLCrBzkG7Q==
hive.api.url=https://api.thehive.ai/api/v3/hive/ai-generated-and-deepfake-content-detection

#Winston
winston.api.key=yCYBdh9Fq8kbpuY7SgmOxI0qb2kQzaoAR58a84Dsdd009d83
winston.api.urltexto=https://api.gowinston.ai/v2/ai-content-detection
winston.api.urlimagen=https://api.gowinston.ai/v2/image-detection

#TEXTO
#GROQ
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
groq.model.vision=meta-llama/llama-4-scout-17b-16e-instruct


#Mistral
mistral.agent.id=ag_019e1e02b939733092428746d2736290
mistral.api.key = kh1fTxoL9GBB5SvndrqXsnFVZ1evAWNB
mistral.api.url=https://api.mistral.ai/v1/agents/completions


#IMAGENES/VIDEO

#Sightengine
sightengine.api.key=hi4fzpFxvTMbbxdnSNRV2A7pQV4w7urW
sightengine.api.user=1963548800
sightengine.models=genai,nudity-2.1

#Twelve labs
#Twelve labs
twelvelabs.api.key=tlk_0GXDRA32G18JCV2H42AW21HVACR0	
twelvelabs.api.url=https://api.twelvelabs.io/v1.3
twelvelabs.index.id=6a03cbeddc224292cde84607

#Hive Video
hive.video.api.key=kmX1dZorgSYSnPQVPGnBEQ==
hive.video.api.url=https://api.thehive.ai/api/v2/task/sync

#Musica
#ACRClouse
acrcloud.api.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI3IiwianRpIjoiNzdlMTI4NGVkNWE0NmI4NzYyMmI2MjYzYzNkYmI1NWEzMGNlMDYzNDVhNmY2YmU0ZDA1MTY2NGNkMGNlZmU3M2NjOTVmYzAyZGI3NjY0NjEiLCJpYXQiOjE3NzkxMDgyNDUuNjA2OTY4LCJuYmYiOjE3NzkxMDgyNDUuNjA2OTcxLCJleHAiOjIwOTQ3Mjc0NDQuMzE3MTIyLCJzdWIiOiIzMzM5NDciLCJzY29wZXMiOlsiYnVja2V0cyIsIndyaXRlLWJ1Y2tldHMiLCJyZWFkLWJ1Y2tldHMiLCJhdWRpb3MiLCJ3cml0ZS1hdWRpb3MiLCJyZWFkLWF1ZGlvcyIsImZpbGVzY2FubmluZyIsIndyaXRlLWZpbGVzY2FubmluZyIsInJlYWQtZmlsZXNjYW5uaW5nIiwibWV0YWRhdGEiLCJyZWFkLW1ldGFkYXRhIl19.Z0WC9MsAEdXJ6w6rnadQt47DY7RBYOfPoQe7o3JDtU-iGE3f3ZZUcQgqbHV5LoT711r2SaMpP5n6n3h46s-uAAoXfW8x_NHf8hGB-yF70lqeXFtZAfA9sKQ8jw6c-NMwsPiry_vo6kIU-OkpGW35FTrFWZg5pkmwlGrHPWuW5YtAlhAldAxK0esH264R4h_OYhJIVqmzxLHoNf3voyfoaD0iK2FIAGIbjkJQwklBw_0Od9pKU5JxLmlW4ZCEc5mdwkPrYrFZ1QtjainFksiiefC1Zk9tHVMQcL0cpo62-kr66qXVfLMrn842gAl8on5OyALIq-qWjyky83N3uaSBRloXTX9SxTj8pXUgLoCdisrBeXtHoEIUrowRJBSpWbG0-lpLnf8gB0o6MXI6lVfoB7wMsnKrGJjyv1RYp-OVauxJCIn4Yq94FeEQSOZYXiGJ7nwVs73bGHVZiTezE0ad8Q7j7WfHVAVaZ80bO7ZFmZP1ywh_qg5Qq_pxjUeBsTe8YQam1WB4qwOSLmaQwcqdG7VygyU1TAFWX430E2eSKpZGyVIcOk9BdTNaM-mfrKhOABWW5egG-dY6SzHoEblY4OTol08uAnFr2L2H1YhAtAslIKeYYDr1kdT1_ZLWwm3XHt823qDWI9xEdyQzTHxDIP5lZAX558PhDJt6pUb4izQ
acrcloud.container.id=31524
acrcloud.api.url=https://api-us-west-2.acrcloud.com/api/fs-containers/
