spring.application.name=detectia
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base3
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
#zeroGPT
zerogpt.api.key=9498077cdemsh8df84799d236a0bp1ef93ejsn815f4f5218cf
zerogpt.api.host=zerogpt.p.rapidapi.com
zerogpt.api.url=https://zerogpt.p.rapidapi.com/api/v1/detectText