spring.application.name=detectia
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base3
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.cache.use_second_level_cache=false
#zeroGPT
zerogpt.api.key=9498077cdemsh8df84799d236a0bp1ef93ejsn815f4f5218cf
zerogpt.api.host=zerogpt.p.rapidapi.com
zerogpt.api.url=https://zerogpt.p.rapidapi.com/api/v1/detectText

#GEMINI
gemini.api.key=AIzaSyDfBM3yn7_45sjSYeTS4hnlHWXv4JAYMps
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

#GROQ
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
groq.model.vision=meta-llama/llama-4-scout-17b-16e-instruct

#Hugging face
hf.api.key=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
hf.api.url=https://api-inference.huggingface.co/models
hf.model.name=openai-community/roberta-base-openai-detector
